using Microsoft.VisualBasic;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Diagnostics;
using System.Windows.Forms;
using System.Linq;
using System.Xml.Linq;
using System.Threading.Tasks;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace FBNS.My.Resources
{

	//This class was auto-generated by the StronglyTypedResourceBuilder
	//class via a tool like ResGen or Visual Studio.
	//To add or remove a member, edit your .ResX file then rerun ResGen
	//with the /str option, or rebuild your VS project.
	///<summary>
	///  A strongly-typed resource class, for looking up localized strings, etc.
	///</summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Microsoft.VisualBasic.HideModuleNameAttribute()]
	static internal class Resources
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		///<summary>
		///  Returns the cached ResourceManager instance used by this class.
		///</summary>
		[System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		static internal global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FBNS.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		///<summary>
		///  Overrides the current thread's CurrentUICulture property for all
		///  resource lookups using this strongly typed resource class.
		///</summary>
		[System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		static internal global::System.Globalization.CultureInfo Culture {
			get { return resourceCulture; }
			set { resourceCulture = value; }
		}

		///<summary>
		///  Looks up a localized string similar to FBNS.
		///</summary>
		static internal string AdditionalText {
			get { return ResourceManager.GetString("AdditionalText", resourceCulture); }
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
		///</summary>
		static internal System.Drawing.Icon favicon {
			get {
				object obj = ResourceManager.GetObject("favicon", resourceCulture);
				return (System.Drawing.Icon)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Byte[].
		///</summary>
		static internal byte[] MetroFramework {
			get {
				object obj = ResourceManager.GetObject("MetroFramework", resourceCulture);
				return Convert.ToByte(obj);
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Byte[].
		///</summary>
		static internal byte[] MetroFramework_Design {
			get {
				object obj = ResourceManager.GetObject("MetroFramework_Design", resourceCulture);
				return Convert.ToByte(obj);
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Byte[].
		///</summary>
		static internal byte[] MetroFramework_Fonts {
			get {
				object obj = ResourceManager.GetObject("MetroFramework_Fonts", resourceCulture);
				return Convert.ToByte(obj);
			}
		}
	}
}
